#!/usr/bin/env bash

# $USER
if [[ "$(uname)" = 'Darwin' ]]; then
	logged_in_user=$(echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ && ! /loginwindow/ {print $3}')
elif [[ "$(uname)" = 'Linux' ]]; then
	[[ -n $(logname >/dev/null 2>&1) ]] && logged_in_user=$(logname) || logged_in_user=$(whoami)
else
	echo "Unknown OS: $(uname). Exiting..."
	exit 1
fi

# $UID
# logged_in_uid=$(id -u "${logged_in_user}")

# $HOME
logged_in_home=$(eval echo "~${logged_in_user}")

# create plugins directory
mkdir -p "${logged_in_home}/.terraform.d/plugins"

# os
if [[ "$(uname)" = 'Darwin' ]]; then
	os='darwin'
elif [[ "$(uname)" = 'Linux' ]]; then
	os='linux'
else
	echo "Unknown OS: $(uname). Exiting..."
	exit 1
fi

# arch
if [[ "$(uname -m)" = 'x86_64' ]]; then
	arch='amd64'
elif [[ "$(uname -m)" = 'arm64' ]]; then
	arch='arm64'
else
	echo "Unknown arch: $(uname -m). Exiting..."
	exit 1
fi

# latest github release of 'dmacvicar/terraform-provider-libvirt'
browser_download_url=$(curl -s https://api.github.com/repos/dmacvicar/terraform-provider-libvirt/releases/latest \
	| grep -Ev "386|freebsd|windows|SHA256" \
	| grep "browser_download_url.*" \
	| cut -d : -f 2,3 \
	| tr -d \" \
	| sed -e 's/^[[:space:]]*//')
# printf "%s\n" "${browser_download_url}"

get_file_url() {
	for i in $1; do
		# match os and arch to url
		# (e.g., 'https://github.com/dmacvicar/terraform-provider-libvirt/.../terraform-provider-libvirt_0.7.4_darwin_amd64.zip' = 'darwin_amd64')
		if [[ $i =~ $os\_$arch ]]; then
			url=$i
		fi
	done
}

download_file() {
	# verify file doesn't exist
	if [[ -f $2 ]]; then
		echo "File $2 already exists. Skipping download..."
		return
	fi

	# download file
	wget -q $1 -O $2
}

unzip_file() {
	# verify plugin doesn't exist
	local filename=$(find $2 -name "terraform-provider-libvirt*" \
		! -name "*.zip" \
		-type f \
		-maxdepth 1)
	if [[ -f "$filename" ]] || [[ -n "$filename" ]]; then
		echo "Plugin terraform-provider-libvirt already exists. Skipping unzip..."
		return
	fi

	# unzip file
	unzip -q $1 -d $2
}

cleanup() {
	local filename=$(find "${logged_in_home}/.terraform.d/plugins" -name $1 \
		-type f \
		-maxdepth 1)
	[[ -f "$filename" ]] && rm -rf "$filename"
}

main() {
	get_file_url "$browser_download_url"
	download_file "$url" "${logged_in_home}/.terraform.d/plugins/${url##*/}"
	unzip_file "${logged_in_home}/.terraform.d/plugins/terraform-provider-libvirt*.zip" "${logged_in_home}/.terraform.d/plugins"
	cleanup "terraform-provider-libvirt*.zip"
}
main

exit 0
