# code: language=ansible

---
- hosts: all
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Enable service nginx and ensure it is not masked
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        masked: no

    - name: Ensure nginx is started
      ansible.builtin.systemd:
        state: started
        name: nginx

    - name: Add ssh key to authorized_keys
      ansible.builtin.authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
