#cloud-config

output: {all: "| tee -a /var/log/cloud-init.log"} # store logs inside vm

timezone: "America/Chicago"

hostname: ubuntu

package_update: true    # default: true
package_upgrade: false  # default: false

apt:
  sources:
    docker.list:
      source: deb https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - qemu-guest-agent
  - wget

ssh_pwauth: true

disable_root: false

chpasswd:
  users:
    - root:toor
  expire: false

users:
  - name: ubuntu
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    groups:
      - admin
      - users
      - wheel
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    ssh_import_id:
      - gh:pythoninthegrass

  - name: ansible
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    groups:
      - admin
      - users
      - wheel
    shell: /bin/bash
    lock_passwd: true
    ssh_import_id:
      - gh:pythoninthegrass

ssh:
  emit_keys_to_console: false

write_files:
  - path: /etc/netplan/01-netcfg.yaml
    owner: root:root
    permissions: '0600'
    append: false
    content: |
      network:
        version: 2
        ethernets:
          ens3:
            dhcp4: true
            nameservers:
              addresses: [8.8.8.8, 8.8.4.4]

runcmd:
  - systemctl enable --now qemu-guest-agent.service
  - mkdir -p /home/ubuntu/.ssh
  - ssh-keyscan github.com >> /home/ubuntu/.ssh/known_hosts
  - chown -R ubuntu:ubuntu /home/ubuntu/.ssh
  - chmod 700 /home/ubuntu/.ssh
  - chmod 600 /home/ubuntu/.ssh/known_hosts
  - mkdir -p /home/ansible/.ssh
  - chown -R ansible:ansible /home/ansible/.ssh
  - chmod 700 /home/ansible/.ssh
  - touch /var/log/ansible.log
  - chown ansible:ansible /var/log/ansible.log
  - chmod 0777 /var/log/ansible.log
  - netplan apply

final_message: "The system is finally up, after $UPTIME seconds"
