version: 2
ethernets:
  ens3:
    dhcp4: false
    addresses:
      - ${vm_ip}/24
    gateway4: 192.168.100.1
    nameservers:
      addresses: [8.8.8.8, 8.8.4.4]
      search: [vm.local]
    routes:
      - to: 10.0.0.0/8
        via: 192.168.100.1
      - to: 172.16.0.0/12
        via: 192.168.100.1
      - to: 203.0.113.0/24
        via: 192.168.100.1
