---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html#examples

- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: add hosts from extra-vars to "temp" group
      add_host:
        groups: temp
        name: "{{ item }}"
      loop: "{{ target_host }}"

- hosts: temp
  gather_facts: true
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Enable service nginx and ensure it is not masked
      systemd:
        name: nginx
        enabled: yes
        masked: no

    - name: ensure nginx is started
      systemd:
        state: started
        name: nginx
